# -*- coding: utf-8 -*-
"""irrigation_env.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14mhZHBPkTOOjpEbW1xXwNKCCFYyzLz2k
"""

import gymnasium as gym
from gymnasium import spaces
import numpy as np
import random

class IrrigationEnv(gym.Env):
    """
    Hybrid Irrigation Environment:
    ✅ Uses realistic crop/soil parameters (opt_m, opt_n)
    ✅ Keeps effective old-style growth & reward dynamics
    ✅ Tuned for stable RL training and strong learning signals
    """
    metadata = {"render.modes": ["human"]}

    def __init__(self, days=30, crop=None, soil=None, seed=None):
        super().__init__()

        if seed is not None:
            np.random.seed(seed)
            random.seed(seed)

        self.max_days = days

        # --- Crop Parameters (realistic optima + growth) ---
        self.crop_data = {
            "maize":  {"opt_m": 0.65, "opt_n": 0.60, "base_growth": 0.03},
            "rice":   {"opt_m": 0.75, "opt_n": 0.55, "base_growth": 0.025},
            "wheat":  {"opt_m": 0.55, "opt_n": 0.50, "base_growth": 0.035},
            "tomato": {"opt_m": 0.60, "opt_n": 0.65, "base_growth": 0.03},
            "soybean":{"opt_m": 0.58, "opt_n": 0.60, "base_growth": 0.028},
            "carrot": {"opt_m": 0.60, "opt_n": 0.58, "base_growth": 0.027},
            "potato": {"opt_m": 0.68, "opt_n": 0.62, "base_growth": 0.028},
            "beans":  {"opt_m": 0.60, "opt_n": 0.60, "base_growth": 0.03},
        }
        self.crop_types = list(self.crop_data.keys())

        # --- Soil Parameters ---
        self.soil_data = {
            "sandy": {"evap_factor": 1.2, "leach_factor": 1.2},
            "loamy": {"evap_factor": 1.0, "leach_factor": 1.0},
            "clay":  {"evap_factor": 0.8, "leach_factor": 0.8},
        }
        self.soil_types = list(self.soil_data.keys())

        # Assign crop/soil
        self.crop = crop if crop in self.crop_types else random.choice(self.crop_types)
        self.soil = soil if soil in self.soil_types else random.choice(self.soil_types)

        # --- Action Space (Continuous: irrigation, fertilizer) ---
        self.action_space = spaces.Box(low=np.array([0.0, 0.0]),
                                       high=np.array([0.1, 0.05]),
                                       dtype=np.float32)

        # --- Observation Space (M, N, G, day_norm, crop_onehot, soil_onehot) ---
        obs_size = 3 + 1 + len(self.crop_types) + len(self.soil_types)
        self.observation_space = spaces.Box(low=0, high=1, shape=(obs_size,), dtype=np.float32)

        self.reset()

    # -------------------------------------------------------------- #
    def reset(self, *, crop=None, soil=None, **kwargs):
        self.crop = crop if crop in self.crop_types else random.choice(self.crop_types)
        self.soil = soil if soil in self.soil_types else random.choice(self.soil_types)

        params = self.crop_data[self.crop]
        self.opt_m = params["opt_m"]
        self.opt_n = params["opt_n"]
        self.base_growth = params["base_growth"]

        soil_params = self.soil_data[self.soil]
        self.evap_factor = soil_params["evap_factor"]
        self.leach_factor = soil_params["leach_factor"]

        self.day = 0
        self.M = np.random.uniform(0.3, 0.5)
        self.N = np.random.uniform(0.3, 0.5)
        self.G = 0.05

        self.total_water = 0.0
        self.total_fertilizer = 0.0
        self.total_leaching = 0.0

        return self._get_obs(), {}

    # -------------------------------------------------------------- #
    def _get_obs(self):
        day_norm = self.day / self.max_days
        crop_onehot = [1.0 if c == self.crop else 0.0 for c in self.crop_types]
        soil_onehot = [1.0 if s == self.soil else 0.0 for s in self.soil_types]
        return np.array([self.M, self.N, self.G, day_norm] + crop_onehot + soil_onehot, dtype=np.float32)

    # -------------------------------------------------------------- #
    def step(self, action):
        irrigation = float(np.clip(action[0], 0, 0.1))
        fertilizer = float(np.clip(action[1], 0, 0.05))

        # --- Weather & Evaporation ---
        rain = np.random.uniform(0, 0.05) if np.random.rand() < 0.2 else 0
        evap = self.evap_factor * np.random.uniform(0.015, 0.025)

        # --- Water & Nutrient Dynamics ---
        self.M = np.clip(self.M + irrigation + rain - evap, 0, 1)
        leaching = self.leach_factor * 0.01 * max(0, self.M - 0.6)
        uptake = 0.02 * self.G * self.M
        self.N = np.clip(self.N + fertilizer - uptake - leaching, 0, 1)

        # --- Growth (from old model, tuned for realism) ---
        effective_M = min(self.M / self.opt_m, 1.2)
        effective_N = min(self.N / self.opt_n, 1.2)
        growth_rate = self.base_growth * effective_M * effective_N * (1 - self.G)
        growth_rate = np.clip(growth_rate, 0, 0.03)
        self.G = np.clip(self.G + growth_rate, 0, 1)

        # --- Reward (from old model, proven stable) ---
        reward = 10 * growth_rate - 3 * irrigation - 2 * fertilizer - 5 * leaching

        # --- Day update ---
        self.day += 1
        terminated = self.day >= self.max_days
        truncated = False

        if terminated:
            reward += 100 * self.G  # final yield bonus

        # --- Totals ---
        self.total_water += irrigation
        self.total_fertilizer += fertilizer
        self.total_leaching += leaching

        obs = self._get_obs()
        info = {
            "crop": self.crop,
            "soil": self.soil,
            "growth_rate": growth_rate,
            "leaching": leaching,
            "total_water": self.total_water,
            "total_fertilizer": self.total_fertilizer,
            "total_leaching": self.total_leaching,
        }

        return obs, reward, terminated, truncated, info

    # -------------------------------------------------------------- #
    def render(self, mode="human"):
        print(f"Day {self.day}: Crop={self.crop}, Soil={self.soil}, "
              f"M={self.M:.2f}, N={self.N:.2f}, G={self.G:.2f}")


# ---------------------- Quick Test ---------------------- #
if __name__ == "__main__":
    env = IrrigationEnv(days=30)
    obs, _ = env.reset()
    print("Initial observation:", obs)
    for t in range(30):
        action = env.action_space.sample()
        obs, reward, terminated, truncated, info = env.step(action)
        env.render()
        if terminated or truncated:
            break

